
---
- name: apt update and install curl
  hosts: all
  become: yes 
  tasks:
  - name: update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: install curl
    apt: name=curl state=latest
 
  - name: Enable UFW and allow ports TCP 80,8080,1834 
    ufw:
     state: enabled
     rule: allow
     port: 80,8080,1834
     proto: tcp

  - name: Change ssh port and PasswordAuthen=1
    lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "^Port"
     line: "Port 1834"

  - name: user add
    user:
     name: "{{ item.name }}"        
     password: "{{ item.password }}"

    with_items:
     - { name: Webdeveloper, password: S52we9V6QTp76 }
     - { name: Devopsengineer, password: dHy6sKGHsj2T }
     - { name: Projectmanager, password: oP92ugMSaCbe }


  - name: install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  
  - name: add docker key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: Add docker rep
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present
  
  - name: Update apt and install ce
    apt: update_cache=yes name=docker-ce state=latest
 
  - name: install pip
    pip:
     name: docker

  - name: mkdir
    file:
     path: /skillcloud-nginx
     state: directory
     mode: '755'

  
  - name: copy files to skillcloud
    copy:
     src: Project_Deployer/{{ item }}
     dest: /skillcloud-nginx/{{ item }}
    loop: [ 'index.html', 'nginx.conf', 'docker-compose.sh', 'docker-compose.yml']
 

  - name: Reboot
    reboot:
